Update config.js
Evavic44/adocs pull request #14
Opened 2024-01-01 18:04 UTC by Heus-Sueh

adding lang, cleanUrls, ignoreDeadLinks, docFooter and related settings to the mobile page

2024-01-02 23:30 UTC, Heus-Sueh commented
added **editLink**

2024-01-03 13:52 UTC, Evavic44 requested changes
Thanks for the PR. Please fix the issues so I can merge it.

2024-01-03 13:52 UTC, Evavic44 commented on docs/.vitepress/config.js
> +    editLink: {
Edit link not working. Should follow [docs format](https://vitepress.dev/reference/default-theme-config#editlink)
```js
https://github.com/Evavic44/adocs/edit/main/docs/:path
```

2024-01-03 14:02 UTC, Heus-Sueh commented
> Thanks for the PR. Please fix the issues so I can merge it.

Okay, I hadn't seen the error before

2024-01-03 14:09 UTC, merged